stages:
  - build
  - test
  - staging
  - deploy

default:
  image: eclipse-temurin:20

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

build-job:
  stage: build
  script:
    - apt-get update && apt-get install -y maven
    - mvn -version
    - mvn clean
    - mvn install
    - mvn compile
  when: delayed
  start_in: 1 minute
  artifacts:
    paths:
      - "build/"
    expire_in: 1 day