stages:
  - build
  - test
  - release image
  - staging
  - deploy

default:
  image: eclipse-temurin:20

#workflow:
#  rules:
#    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

build-job:
  stage: build
  tags:
    - vps
  script:
    - apt-get update && apt-get install -y maven
    - mvn clean
    - mvn compile
    - mvn package
  start_in: 5 seconds
  when: delayed
  except:
    changes:
      - "*.md" #you don't want to run pipeline if it's not contains changes in readme
  artifacts:
    paths:
      - "target/*.jar"
    expire_in: 1 day