stages:
  - build
  - test
  - release image
  - staging
  - deploy

default:
  image: eclipse-temurin:20

#variables:
#  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dstyle.color=always"

#workflow:
#  rules:
#    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

cache:
  - key: dependencies
    paths:
      - .m2

build-job:
  stage: build
  tags:
    - vps #tag to vps runner
#  services:
#    - name: postgres:alpine
#      alias: mydb
  script:
    - apt-get update && apt-get install -y maven
    - mvn clean
    - mvn compile
    - mvn package
  start_in: 5 seconds
  when: delayed
  except:
    changes:
      - "*.md" #you don't want to run pipeline if it's not contains changes in readme
  artifacts:
    paths:
      - "target/*.jar"
    expire_in: 1 day