image: eclipse-temurin:20

build-job:
#  image: eclipse-temurin:20-alpine
  script:
    - apt-get update && apt-get install -y maven
    - mvn -version
    - mvn clean
    - mvn install
    - mvn compile
  artifacts:
    paths:
      - "build"